name: build windows

on:
  workflow_call:
    inputs:
      boost:
        type: boolean
        description: "Whether to use Boost or not"
        required: true
        default: true
      boost_version:
        type: string
        description: "The Boost version to use"
        required: true
        default: "1.81.0"

jobs:
  windows-2022:
    strategy:
      max-parallel: 1
      matrix:
        platform_version: [2022]
        toolset: [msvc]
        link: [shared]
        arch: [x86]

    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
        if: matrix.toolset == 'msvc'

      - name: Download and install Boost
        if: ${{ inputs.boost == true }}
        id: download_boost
        uses: MarkusJx/install-boost@v2.4.4
        with:
          boost_version: ${{ inputs.boost_version }}
          platform_version: ${{ matrix.platform_version }}
          toolset: ${{ matrix.toolset }}
          link: ${{ matrix.link }}

      - name: Move Boost to root
        if: ${{ inputs.boost == true }}
        run: move ${{ steps.download_boost.outputs.BOOST_ROOT }} C:\\

      - name: Meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          meson-version: 1.1.0

      - uses: actions/cache@v3
        with:
          path: build
          key: build-windows

  windows-2019:
    strategy:
      max-parallel: 1
      matrix:
        platform_version: [2019]
        toolset: [msvc]
        link: [shared]
        arch: [x86]

    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
        if: matrix.toolset == 'msvc'

      - name: Download and install Boost
        if: ${{ inputs.boost == true }}
        id: download_boost
        uses: MarkusJx/install-boost@v2.4.4
        with:
          boost_version: ${{ inputs.boost_version }}
          platform_version: ${{ matrix.platform_version }}
          toolset: ${{ matrix.toolset }}
          link: ${{ matrix.link }}

      - name: Move Boost to root
        if: ${{ inputs.boost == true }}
        run: move ${{ steps.download_boost.outputs.BOOST_ROOT }} C:\\

      - name: Meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          meson-version: 1.1.0
