name: build linux

on:
  workflow_call:
    inputs:
      boost:
        type: boolean
        description: "Whether to use Boost or not"
        required: true
        default: true
      boost_version:
        type: string
        description: "The Boost version to use"
        required: true
        default: "1.81.0"

jobs:
  ubuntu-2204:
    strategy:
      max-parallel: 1
      matrix:
        platform_version: [22.04]
        toolset: [gcc]
        link: [static+shared]
        arch: [aarch64]

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install Boost
        if: ${{ inputs.boost == true }}
        uses: MarkusJx/install-boost@v2.4.4
        id: download_boost
        with:
          boost_version: ${{ inputs.boost_version }}
          platform_version: ${{ matrix.platform_version }}
          toolset: ${{ matrix.toolset }}
          link: ${{ matrix.link }}

      - name: move Boost
        if: ${{ inputs.boost == true }}
        run: |
          sudo mv ${{ steps.download_boost.outputs.BOOST_ROOT }}/include/boost /usr/local/include
          sudo mv ${{ steps.download_boost.outputs.BOOST_ROOT }}/lib/*.so /usr/local/lib

      - name: Meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          meson-version: 1.1.0

      - uses: actions/cache@v3
        with:
          path: build
          key: build-linux

  ubuntu-2004:
    strategy:
      max-parallel: 1
      matrix:
        platform_version: [20.04]
        toolset: [gcc]
        link: [static+shared]
        arch: [aarch64]

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install Boost
        if: ${{ inputs.boost == true }}
        uses: MarkusJx/install-boost@v2.4.4
        id: download_boost
        with:
          boost_version: ${{ inputs.boost_version }}
          platform_version: ${{ matrix.platform_version }}
          toolset: ${{ matrix.toolset }}
          link: ${{ matrix.link }}

      - name: move Boost
        if: ${{ inputs.boost == true }}
        run: |
          sudo mv ${{ steps.download_boost.outputs.BOOST_ROOT }}/include/boost /usr/local/include
          sudo mv ${{ steps.download_boost.outputs.BOOST_ROOT }}/lib/*.so /usr/local/lib

      - name: Meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          meson-version: 1.1.0
